### ISSUE TITLE
Can't grind 404 on production site

### ISSUE THREAD

**Issue by DarrienG** [bmstefanski/sigma-male-grindset-api#1]
Feeling beta ngl

![Screen Shot 2021-08-23 at 12 41 03](https://user-images.githubusercontent.com/5041953/130484938-9817ccd4-2d09-4af0-be08-eb2b6d84e4c9.png)

**Comment by DarrienG** [comment]
Oh wait the main site link is clickable but you're only supposed to hit the APIs.

Exposing my inner beta 😔

**Comment by bmstefanski** [comment]
up your grindset @DarrienG

**Comment by bmstefanski** [comment]
with love <3
